spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Admin@123
    url: jdbc:mysql://localhost:3306/capstone
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    try-it-out-enabled: false
    default-model-expand-depth: -1